### ISSUE TITLE
ROS buildfarm Noetic: libpcl-dev breaking libvtk6-dev and libvtk6-qt-dev

### ISSUE THREAD

**Issue by matlabbe** [introlab/rtabmap#557]
Full log: http://build.ros.org/job/Nbin_uF64__rtabmap__ubuntu_focal_amd64__binary/1/consoleFull

```
10:22:03 The following packages have unmet dependencies:
10:22:03  libpcl-dev : Breaks: libvtk6-dev but 6.3.0+dfsg2-5build2 is to be installed
10:22:03               Breaks: libvtk6-qt-dev but 6.3.0+dfsg2-5build2 is to be installed
```

On Focal, `libpcl-dev` is depending on `libvtk7-dev`. RTAB-Map needs qt libraries of vtk, so normally `libvtk7-qt-dev` should work (tested locally and it works). However, rosdistro's dependencies for `libvtk-qt` (see rtabmap's package.xml):
https://github.com/introlab/rtabmap/blob/c7be9a23ee9fece1a6938b5efe37993df2b9bb54/package.xml#L21

 are ([rosdistro](https://github.com/ros/rosdistro/blob/504a87eed1f7da15db1e5b56ec83e910cb8dc2a1/rosdep/base.yaml#L4118)): 
```
libvtk-qt:
  arch: [vtk]
  debian:
    buster: [libvtk6-qt-dev]
    jessie: [libvtk5-qt4-dev]
    stretch: [libvtk6-qt-dev]
    wheezy: [libvtk5-qt4-dev]
  fedora: [vtk-qt]
  freebsd: [vtk6]
  gentoo: ['sci-libs/vtk[qt5,rendering]']
  opensuse: [vtk-qt]
  slackware: [VTK]
  ubuntu:
    '*': [libvtk6-qt-dev]
    lucid: [libvtk5-qt4-dev]
    maverick: [libvtk5-qt4-dev]
    natty: [libvtk5-qt4-dev]
    oneiric: [libvtk5-qt4-dev]
    precise: [libvtk5-qt4-dev]
    quantal: [libvtk5-qt4-dev]
    raring: [libvtk5-qt4-dev]
    saucy: [libvtk5-qt4-dev]
    trusty: [libvtk5-qt4-dev]
    utopic: [libvtk5-qt4-dev]
    vivid: [libvtk5-qt4-dev]
    wily: [libvtk5-qt4-dev]
```
refering to `libvtk6-qt-dev` instead of `libvtk7-qt-dev`, breaking `libpcl-dev` package. RTAB-Map needs both `libpcl-dev` and `libvtk7-qt-dev`, how can we do that?
