### ISSUE TITLE
util3d_features.cpp generateKeypoints3dDepth() uassert fails

### ISSUE THREAD

**Issue by scott-eddy** [introlab/rtabmap#64]
I am trying to run rtabmap.launch with an intel realsense R200. I've changed the rgb_topic, depth-topic, and camera_info_topic to the proper names but am running into a fatal error:
`[FATAL] (2016-03-25 15:26:20.417) util3d_features.cpp:89::generateKeypoints3DDepth() Condition (cameraIndex >= 0 && cameraIndex < (int)cameraModels.size()) not met! [cameraIndex=1, models=1, kpt.x=546.000000, subImageWidth=480.000000 (Camera model image width=0)]`

Obviously it is failing because cameraIndex = cameraModels.size() == 1, but I don't understand why that is a problem.  I was wondering i anyone can provide me with some clarity as to what [this](https://github.com/introlab/rtabmap/blob/master/corelib/src/util3d_features.cpp#L87) assertion is demanding.   Why would one camera model for one color camera be a problem?

Thanks!

**Comment by matlabbe** [comment]
Are your RGB and depth images are the same size? It seems not. Hopefully, the rtabmap version (0.11) you are using supports RGB and depth images with not the same size (so you would not have to resize the RGB or the depth image). The error above tells that image size of the camera model is null (`Camera model image width=0`). Make sure the `camera_info` msg contains the image size set. The conversion between ROS camera model to RTAB-Map camera model is done [here](https://github.com/introlab/rtabmap_ros/blob/f26c8b55eb0b48b8b5de48a0632e9811e47ff6b2/src/MsgConversion.cpp#L329-L342). Looking at [sensor_msgs/CameraInfo](http://docs.ros.org/api/sensor_msgs/html/msg/CameraInfo.html) message, the fields `width` and `height` should be set.

``` bash
$ rostopic echo /rgb/camera_info
```
 If they are null, you would have to update the R200 package publishing the `camera_info` to include them or create a node republishing the same `camera_info` but with the resolution set.

cheers

**Comment by scott-eddy** [comment]
@matlabbe thanks for the prompt reply.  My depth and RGB images are not the same size, but I cam using rtab map version 0.11.2.  Unfortunately, the image size of the model is reported correctly in camera info.  The output of echoing the topic is:
``` 
seq: 383
  stamp:
    secs: 1459076138
    nsecs: 252774570
  frame_id: camera_rgb_optical_frame
height: 480
width: 640
distortion_model: plumb_bob
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [616.394287109375, 0.0, 323.9136657714844, 0.0, 622.3211669921875, 242.3827362060547, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [616.394287109375, 0.0, 323.9136657714844, 0.0, 0.0, 622.3211669921875, 242.3827362060547, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
Any reason why the ROI width/height would be confused with the actual width/height?
