### ISSUE TITLE
about CameraRGBDImages()

### ISSUE THREAD

**Issue by Wade5566** [introlab/rtabmap#66]
Hi,

Thanks for the wonderful project.
I want to use the CameraRGBDImages() by the images and depth maps captured by ASUS Xtion Pro Live.
But it said that **Rectified image required! Calibrate your camera!** and **no odometry is provided**. 
How can I do?
Thank you.

**Comment by matlabbe** [comment]
A calibration file should be given to [CameraRGBDImages object on initialization](https://github.com/introlab/rtabmap/blob/bcd96a97a3fca3a0e419829598a16aafed11ddb9/corelib/include/rtabmap/core/CameraRGBD.h#L289).

Example of a minimal calibration file (assuming that images are rectified and depth is already registered to RGB) arbitrarly called `xtion.yaml` (**note that values are based on Kinect, you may have to change fx and fy**) in the same directory as the executable:
```yaml
%YAML:1.0
camera_name: xtion
image_width: 640
image_height: 480
camera_matrix:
   rows: 3
   cols: 3
   data: [ 525, 0., 525, 0., 319.5,
       239.5, 0., 0., 1. ]
```

```c++
CameraRGBDImages camera;
camera.init(".", "xtion");
```
