### ISSUE TITLE
Map upside down with imu

### ISSUE THREAD

**Issue by skymaze** [introlab/rtabmap#927]
Hi, the 3d map is upside down when using imu. what could be the problem? Thanks.
Imu reading.
```
header:
  stamp:
    sec: 1668596142
    nanosec: 768519702
  frame_id: imu_link
orientation:
  x: -0.49842551350593567
  y: -0.866909921169281
  z: -0.004570078104734421
  w: 0.004293754696846008
orientation_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: 0.00043676397763192654
  y: 0.0009418718400411308
  z: -0.00016067991964519024
angular_velocity_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: -0.1024266704916954
  y: -0.04085110127925873
  z: 9.771583557128906
linear_acceleration_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```

Imu link
```
<link name="imu_link"></link>
<joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x_offset} ${imu_y_offset} ${imu_z_offset}" rpy="0 0 0" />
</joint>
```
